schema_version = "1.4"

[task]
name = "browserbase/agent-hugging-face"

[metadata]
suite = "agent"
task_id = "agent-hugging-face"

[environment]
network_mode = "public"

[agent]
timeout_sec = 900

[verifier]
timeout_sec = 900
environment_mode = "shared"
