schema_version = "1.4"

[task]
name = "browserbase/agent-github-react-version"

[metadata]
suite = "agent"
task_id = "agent-github-react-version"

[environment]
network_mode = "public"

[agent]
timeout_sec = 900

[verifier]
timeout_sec = 900
environment_mode = "shared"
